Task1: 

In [ ]:
"Day 2"
# Here i create a 4x4 array by using linspace where the numbers start at 1 and end at 16 with 16 even seperations and then reshape it to be a 2d matrix with 4 rows and 4 columns
import numpy as np
array = np.linspace(1,16,16).reshape(4,4)
print(array)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


Task 2:

In [ ]:
# Here i exract the second column of the last row, -1 indicates the first row from the opposite side (last one) and 1 is the second element
second_column_of_last_row= array[-1,1]
print(second_column_of_last_row)

14.0


Task 3:

In [ ]:
#Here i use boolean masking to find the values that are greater than the mean value of the array
mean_value = array.mean()
values_greater_than_mean = array[array>mean_value]
print(f"Mean: {mean_value}",values_greater_than_mean)

Mean: 8.5 [ 9. 10. 11. 12. 13. 14. 15. 16.]


Task 4:


In [ ]:
# Create an array of 10s by creating an array of 1s and multiplying it with 10
array_of_10s = np.ones((1,4)) * 10
# Add 10 to every element
broadcasted_array=array+array_of_10s
print(broadcasted_array)

[[11. 12. 13. 14.]
 [15. 16. 17. 18.]
 [19. 20. 21. 22.]
 [23. 24. 25. 26.]]
